# Generated by Django 5.0.4 on 2024-04-23 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WoodFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, max_length=500, null=True)),
                ('domestic', models.BooleanField(default=True)),
                ('hardwood', models.BooleanField(default=True)),
                ('density', models.FloatField(null=True)),
                ('origin', models.CharField(blank=True, max_length=500, null=True)),
                ('appearance', models.CharField(blank=True, max_length=500, null=True)),
                ('characteristics', models.CharField(blank=True, max_length=500, null=True)),
                ('colorCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woods_of_this_colorCat', to='calcapi.colorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('length', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('thickness', models.IntegerField(null=True)),
                ('totalBF', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_added_by_this_user', to=settings.AUTH_USER_MODEL)),
                ('wood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_of_this_wood_type', to='calcapi.wood')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_of_this_format', to='calcapi.woodformat')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
