# Generated by Django 5.0.4 on 2024-04-23 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapi', '0002_colorcategory_woodformat_wood_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wood',
            name='image',
            field=models.ImageField(null=True, upload_to='images/woods', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='entry_date',
            field=models.DateTimeField(verbose_name='date entered'),
        ),
        migrations.AlterField(
            model_name='wood',
            name='density',
            field=models.IntegerField(null=True),
        ),
    ]
