# Generated by Django 5.0.4 on 2024-04-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapi', '0003_wood_image_alter_inventory_entry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='wood',
        ),
        migrations.AddField(
            model_name='inventory',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_of_this_wood_species', to='calcapi.wood'),
        ),
    ]
