# Generated by Django 5.0.4 on 2024-04-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapi', '0007_alter_inventory_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='thickness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='totalBF',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
