# Generated by Django 5.0.4 on 2024-05-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapi', '0008_alter_inventory_length_alter_inventory_thickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
